CREATE TABLE IF NOT EXISTS data (
from TEXT NULL,
img_name TEXT NULL,
is_fav TEXT NULL,
Quote TEXT NULL
);

INSERT INTO data VALUES
("Ilka Chase","Ilka_Chase.jpg","false","The only people who never fail are those who never try."),
("Marian Wright Edelman","Marian_Wright_Edelman.jpg","false","Failure is just another way to learn how to do something right."),
("Thomas Edison","Thomas_Edison.jpg","false","I failed my way to success."),
("Napoleon Hill","Napoleon_Hill.jpg","false","Every failure brings with it the seed of an equivalent success."),
("John F. Kennedy","John_F._Kennedy.jpg","false","Only those who dare to fail greatly can ever achieve greatly."),
("Theodore Roosevelt","Theodore_Roosevelt.jpg","false","It is hard to fail\, but it is worse never to have tried to succeed."),
("Albert Einstein","Albert_Einstein.jpg","false","Imagination is more important than knowledge."),
("Langston Hughes","Langston_Hughes.jpg","false","Hold fast to dreams\, for if dreams die\, life is a broken winged bird that cannot fly."),
("Eleanor Roosevelt","Eleanor_Roosevelt.jpg","false","The future belongs to those who believe in the beauty of their dreams."),
("Henry David Thoreau","Henry_David_Thoreau.jpg","false","Go confidently in the direction of your dreams. Live the life you have imagined."),
("Mark Twain","Mark_Twain.jpg","false","You cannot depend on your eyes when your imagination is out of focus."),
("Marcia Wieder","Marcia_Wieder.jpg","false","Commitment leads to action. Action brings your dream closer."),
("Unknown","profile.png","false","I never think of the future it comes soon enough"),
("Ralph Waldo Emerson","Ralph_Waldo_Emerson.jpg","false","Don't waste your life in doubts and fears: Spend yourself on the work before you\, well assured that the right performance of this hour's duties will be the best preparation for the hours or ages that follow it."),
("Benjamin Franklin","Benjamin_Franklin.jpg","false","Do not anticipate trouble or worry about what may never happen. Keep in the sunlight."),
("Andrew Jackson","Andrew_Jackson.jpg","false","Take time to deliberate; but when the time for action arrives\, stop thinking and go in."),
("Seneca","Seneca.jpg","false","The mind that is anxious about future events is miserable."),
("Henry David Thoreau","Henry_David_Thoreau.jpg","false","Live in each season as it passes; breathe the air\, drink the drink\, taste the fruit\, and resign yourself to the influences of each."),
("Tony Blair","Tony_Blair.jpg","false","The art of leadership is saying no\, not yes. It is very easy to say yes."),
("Napoleon Bonaparte","Napoleon_Bonaparte.jpg","false","A leader is a dealer in hope."),
("John C. Maxwell","John_C._Maxwell.jpg","false","While a good leader sustains momentum\, a great leader increases it."),
("General Douglas MacArthur","General_Douglas_MacArthur.jpg","false","A general is just as good or just as bad as the troops under his command make him."),
("Friedrich Nietzsche","Friedrich_Nietzsche.jpg","false","To do great things is difficult; but to command great things is more difficult."),
("Woodrow Wilson","Woodrow_Wilson.png","false","Leadership does not always wear the harness of compromise."),
("Unkown","profile.png","false","Business opportunities are like buses there's always another one coming."),
("Charlotte Bronte","Charlotte_Bronte.jpg","false","I avoid looking forward or backward\, and try to keep looking upward."),
("Horace Bushnell","Horace_Bushnell.jpg","false","The more difficulties one has to encounter\, within and without\, the more significant and the higher in inspiration his life will be."),
("Ralph Waldo Emerson","Ralph_Waldo_Emerson.jpg","false","Every artist was first an amateur."),
("Anna Freud","Anna_Freud.jpg","false","I was always looking outside myself for strength and confidence\, but it comes from within. It is there all of the time."),
("Helen Keller","Helen_Keller.jpg","false","We can do anything we want to do if we stick to it long enough."),
("E. Joseph Cossman","E._Joseph_Cossman.jpg","false","Our business in life is not to get ahead of others\, but to get ahead of ourselves."),
("Ralph Waldo Emerson","Ralph_Waldo_Emerson.jpg","false","Insist on yourself. Never imitate."),
("Carl Jung","Carl_Jung.jpg","false","Who looks outside\, dreams. Who looks inside\, awakes."),
("Agnes Repplier","Agnes_Repplier.jpg","false","It is not easy to find happiness in ourselves\, and it is not possible to find it elsewhere."),
("Rainer Maria Rilke","Rainer_Maria_Rilke.jpg","false","The only journey is the one within."),
("William Thackeray","William_Thackeray.jpg","false","Follow your honest convictions\, and stay strong."),
("Marcus Aurelius","Marcus_Aurelius.jpg","false","The happiness of your life depends upon the quality of your thoughts; therefore guard accordingly."),
("Benjamin Disraeli","Benjamin_Disraeli.jpg","false","Action may not always bring happiness; but there is no happiness without action."),
("Benjamin Franklin","Benjamin_Disraeli.jpg","false","Happiness depends more on the inward disposition of mind than on outward circumstances."),
("Henry Ford","Henry_Ford.jpg","false","There is no happiness except in the realization that we have accomplished something."),
("Eleanor Roosevelt","Eleanor_Roosevelt.jpg","false","Happiness is not a goal\, but a by-product."),
("Margaret Lee Runbeck","Margaret_Lee_Runbeck.jpg","false","Happiness is not a state to arrive at\, but a manner of traveling."),
("C. H. Parkhurst","C._H._Parkhurst.jpg","false","Purpose is what gives life a meaning."),
("Kahlil Gibran","Kahlil_Gibran.jpg","false","The significance of a man is not in what he attains but in what he longs to attain."),
("Solon","Solon.jpg","false","In all things that you do\, consider the end."),
("Viktor Frankl","Viktor_Frankl.jpg","false","Life can be pulled by goals just as surely as it can be pushed by drives."),
("Richard Monckton Milnes","Richard_Monckton_Milnes.jpg","false","The virtue lies in the struggle\, not in the prize."),
("Unknown","profile.png","false","To reach a port\, we must sail\, not tie at anchor"),
("Benjamin Disraeli","Benjamin_Disraeli.jpg","false","Success is the child of audacity."),
("Vince Lombardi","Vince_Lombardi.jpg","false","The difference between a successful person and others is not a lack of strength\, not a lack of knowledge\, but rather a lack in will."),
("Aristotle Onassis","Aristotle_Onassis.jpg","false","The secret of success is to know something nobody else knows."),
("Richard Brinsley Sheridan","Richard_Brinsley_Sheridan.jpg","false","The surest way not to fail is to determine to succeed."),
("Unknown.","profile.png","false","I cannot give you the formula for success\, but I can give you the formula for failure which is: Try to please everybody"),
("Ullery","Aristotle_Onassis.jpg","false","Careful thinking and hard work will solve nearly all your problems. Try and see for yourself."),
("Berthold Auerbach","Aristotle_Onassis.jpg","false","Years teach us more than books."),
("Thomas Huxley","Thomas_Huxley.jpg","false","The only medicine for suffering\, crime\, and all the other woes of mankind\, is wisdom."),
("William James","Aristotle_Onassis.jpg","false","The art of being wise is knowing what to overlook."),
("Abraham Maslow","Abraham_Maslow.jpg","false","The great lesson is that the sacred is in the ordinary\, that it is to be found in one's daily life\, in one's neighbors\, friends and family\, in one's backyard."),
("Latin proverb","profile.png","false","A wise man learns by the mistakes of others\, a fool by his own."),
("Seneca","Aristotle_Onassis.jpg","false","No man was ever wise by chance."),
("Victor Cousins","Victor_Cousins.jpg","false","In everything the ends well defined are the secret of durable success."),
("John Dewey","Aristotle_Onassis.jpg","false","Arriving at one goal is the starting point to another."),
("Napoleon Hill","Napoleon_Hill.jpg","false","A goal is a dream with a deadline."),
("Don Lancaster","Aristotle_Onassis.jpg","false","Most 'impossible' goals can be met simply by breaking them down into bite-size chunks\, writing them down\, believing them\, and then going full speed ahead as if they were routine."),
("Brian Tracy","Aristotle_Onassis.jpg","false","Goals are the fuel in the furnace of achievement."),
("Aristotle","Aristotle_Onassis.jpg","false","We are what we repeatedly do. Excellence\, therefore\, is not an act but a habit."),
("Bobby Flay","Aristotle_Onassis.jpg","false","Take risks and you'll get the payoffs. Learn from your mistakes until you succeed. It's that simple."),
("Robert Frost","Aristotle_Onassis.jpg","false","The best way out is always through."),
("Wayne Gretzky","Aristotle_Onassis.jpg","false","You miss 100 percent of the shots you don't take."),
("Samuel Johnson","Aristotle_Onassis.jpg","false","Nothing will ever be attempted if all possible objections must first be overcome."),
("David Ogilvy","Aristotle_Onassis.jpg","false","Don't bunt. Aim out of the ballpark."),
("Nolan Bushnell\, entrepreneur.","Aristotle_Onassis.jpg","false","The critical ingredient is getting off your butt and doing something. It’s as simple as that. A lot of people have ideas\, but there are few who decide to do something about them now. Not tomorrow. Not next week. But today. The true entrepreneur is a doer\, not a dreamer.”"),
("Winston Churchill.","Winston_Churchill.jpg","false","Never give in"),
("Bill Gates.","Bill_Gates.jpg","false","Your most unhappy customers are your greatest source of learning."),
("Thomas Edison\, inventor.","Thomas_Edison.jpg","false","I have not failed. I’ve just found 10\,000 ways that won’t work."),
("Peter Drucker.","Aristotle_Onassis.jpg","false","Entrepreneurship is neither a science nor an art. It is a practice."),
("David Ogilvy.","Aristotle_Onassis.jpg","false","In the modern world of business\, it is useless to be a creative\, original thinker unless you can also sell what you create."),
("General George Patton.","Aristotle_Onassis.jpg","false","Success is how high you bounce after you hit bottom."),
("Reid Hoffman.","Reid_Hoffman.jpg","false","“If you’re not embarrassed by the first version of your product\, you’ve launched too late.”"),
("Zig Ziglar.","Zig_Ziglar.jpg",NULL,"Positive thinking will let you do everything better than negative thinking will."),
("Jay Z.","profile.png","false","“I’m not afraid of dying\, I’m afraid of not trying.”"),
("Dr. Napoleon Hill.","Napoleon_Hill.jpg","false","Whatever the mind can conceive and believe\, the mind can achieve."),
("Carrie Wilkerson","Aristotle_Onassis.jpg","false","The longer you’re not taking action the more money you’re losing"),
("Gary Vaynerchuk","Gary_Vaynerchuk.jpg","false","If you live for weekends or vacations\, your shit is broken"),
("Eliza Dushku","Eliza_Dushku.jpg","false","Go Big\, or Go Home"),
("Napoleon Hill","Napoleon_Hill.jpg","false","Most great people have attained their greatest success just one step beyond their greatest failure"),
("Thomas Edison","Thomas_Edison.jpg","false","Opportunity is missed by most people because it is dressed in overalls and looks like work"),
("Ryan Allis","Aristotle_Onassis.jpg","false","Have the end in mind and every day make sure your working towards it"),
("German Proverb","profile.png","false","He who begins many things finishes but few"),
("William James","profile.png","false","The best use of life is to spend it for something that outlasts it"),
("Derek Bok","Derek_Bok.jpg","false","If you think education is expensive\, try ignorance"),
("A student in Warren G. Tracy’s class","profile.png","false","Entrepreneurship is living a few years of your life like most people wont so you can spend the rest of your life like most people can’t"),
("Ted Nicolas","profile.png","false","Lend your friend $20\, if he doesn’t pay you back then he’s not your friend. Money well spent"),
("Bill Gates","Bill_Gates.jpg",NULL,"Be nice to geek’s\, you’ll probably end up working for one"),
(" Tony Hsieh","profile.png","false","To never forget that the most important thing in life is the quality of life we lead"),
("Unknown","profile.png","false","Its better to own the racecourse then the race horse"),
("Chinese Proverb","profile.png","false","When you go to buy\, don’t show your silver"),
("Grace Hopper","Grace_Hopper.jpg","false","It’s easier to ask forgiveness than it is to get permission"),
("Corneille","profile.png","false","To win without risk is to triumph without glory"),
("Abraham Lincoln","Abraham_Lincoln.jpg","false","Example is not the main thing in influencing other people; it’s the only thing"),
("Booker T. Washington","profile.png","false","Associate yourself with people of good quality\, for it is better to be alone than in bad company"),
("Mark Twain","Mark_Twain.jpg","false","Keep away from people who try to belittle your ambitions. Small people always do that\, but the really great make you feel that you\, too\, can become great"),
("Unknown","profile.png","false","There is only one success to be able to spend your life in your own way"),
("Unknown","profile.png","false","You don’t buy a nice car and get rich you get rich and buy a nice car"),
("Japanese Proverb","profile.png","false","Fall seven times\, stand up eight"),
("Mooie","profile.png","false","One day your life will flash before your eyes. Make sure it is worth watching"),
("Dr. Napoleon Hill","Napoleon_Hill.jpg","false","Whatever the mind can conceive and believe\, the mind can achieve"),
("Thomas Alva Edison","Thomas_Edison.jpg","false","I have not failed. I’ve just found 10\,000 ways that won’t work"),
("Unknown","profile.png","false","If you ain’t making waves\, you ain’t kickin’ hard enough"),
("Johann Wolfgang von Goethe","Aristotle_Onassis.jpg","false","What is not started will never get finished"),
("William B. Sprague","William_B._Sprague.jpg","false","Do not wait to strike until the iron is hot; but make it hot by striking"),
("Malcolm Forbes","Malcolm_Forbes.jpg","false","When you cease to dream you cease to live"),
("Roger H. Lincoln","profile.png","false","There are two rules for success. 1) Never tell everything you know."),
("Vidal Sassoon","Vidal_Sassoon.jpg","false","The only place where success comes before work is in the dictionary."),
("Joe Penna","Joe_Penna.jpg","false","Every single person I know who is successful at what they do is successful because they love doing it."),
("Will Smith","Will_Smith.jpg","false","Being realistic is the most commonly traveled road to mediocrity."),
("Thomas J. Watson","Thomas_J._Watson.jpg","false","Whenever an individual or a business decides that success has been attained\, progress stops."),
("Thomas J. Watson","Thomas_J._Watson.jpg","false","To be successful\, you have to have your heart in your business\, and your business in your heart."),
("Claude McDonald","Claude_McDonald.jpg","false","If hard work is the key to success\, most people would rather pick the lock."),
("Earl Wilson","Earl_Wilson.jpg","false","Success is simply a matter of luck. Ask any failure."),
("Arnold Palmer","Arnold_Palmer.jpg","false","The road to success is always under construction."),
("Napoleon Hill","Napoleon_Hill.jpg","false","Anything the mind can conceive and believe\, it can achieve."),
("Napoleon Hill","Napoleon_Hill.jpg","false","Most great people have attained their greatest success just one step beyond their greatest failure."),
("Henry Ford","Henry_Ford.jpg","false","Whether you think you can or you can’t\, you’re right."),
("Robert T. Kiyosaki","Robert_Kiyosaki.png","false","Failure defeats losers\, failure inspires winners."),
("Thomas Edison","Thomas_Edison.jpg","false","I have not failed. I’ve just found 10\,000 ways that won’t work."),
("Emil Motycka","Emil_Motycka.jpg","false","The biggest failure you can have in life is not trying at all."),
("George Burns","George_Burns.jpg","false","I honestly think it is better to be a failure at something you love than to be a success at something you hate."),
("Charles S. Lauer","Aristotle_Onassis.jpg","false","Leaders don’t force people to follow\, they invite them on a journey."),
("Abraham Lincoln","Abraham_Lincoln.jpg","false","Example is not the main thing in influencing other people; it’s the only thing."),
("George Van Valkenburg","profile.png","false","Leadership is doing what is right when no one is watching."),
("Dwight D. Eisenhower","Dwight_D._Eisenhower.jpg","false","Leadership is the art of getting someone else to do something you want done because he wants to do it."),
("E. M. Kelly","E._M._Kelly.jpg","false","The difference between a boss and a leader: a boss says\, ‘Go!’ -a leader says\, ‘Let’s go!’."),
("Charles Maurice","Charles_Maurice.jpg","false","I am more afraid of an army of one hundred sheep led by a lion than an army of one hundred lions led by a sheep."),
("Bertrand Russell","Bertrand_Russell.jpg","false","The whole problem with the world is that fools and fanatics are always so certain of themselves\, but wiser people so full of doubts."),
("Aristotle","Aristotle_Onassis.jpg","false","We are what we repeatedly do. Excellence\, then\, is not an act\, but a habit."),
("Stanislaw Lem","Stanislaw_Lem.png","false","Cannibals prefer those who have no spines."),
("William Shedd","William_Shedd.jpg","false","A ship in harbor is safe. But that’s now what ships are built for."),
("Lucius Annaeus Seneca","Lucius_Annaeus_Seneca.jpg","false","If one does not know to which port one is sailing\, no wind is favorable."),
("Wayne Gretzky","Wayne_Gretzky.jpg","false","You miss 100% of the shots you don’t take."),
("Jay-Z","profile.png","false","I’m not a businessman. I’m a business\, man."),
("Vance Hayner","profile.png","false","The vision must be followed by the venture. It is not enough to stare up the steps – we must step up the stairs."),
("William B. Sprague","William_B._Sprague.jpg","false","Do not wait to strike until the iron is hot; but make it hot by striking."),
("Grace Hopper","Grace_Hopper.jpg","false","It’s easier to ask forgiveness than it is to get permission."),
("Mark Twain","Mark_Twain.jpg","false","Twenty years from now you will be more disappointed by the things that you didn’t do than by the ones you did do."),
("Mooie","profile.png","false","One day your life will flash before your eyes. Make sure it is worth watching."),
("Steven Wright","Steven_Wright.jpg","false","I think it’s wrong that only one company makes the game Monopoly."),
("Steven Wright","Steven_Wright.jpg","false","Ever notice how it’s a penny for your thoughts\, yet you put in your two-cents? Someone is making a penny on the deal."),
("Karl Marx","Karl_Marx.jpg","false","Catch a man a fish\, and you can sell it to him. Teach a man to fish\, and you ruin a wonderful business opportunity."),
("Les Dawson","Les_Dawson.jpg","false","I used to sell furniture for a living. The trouble was\, it was my own."),
("Charles Steinmetz","Charles_Steinmetz.jpg","false","Marking dynamos for repair $10\,000.00—2 hours labor $10.00; knowing where to mark $9\,990.00."),
("Robert Frost","Robert_Frost.jpg","false","By working faithfully eight hours a day you may eventually get to be boss and work twelve hours a day."),
("Ted Turner","Ted_Turner.jpg","false","My son is now an ‘entrepreneur’. That’s what you’re called when you don’t have a job."),
("Mitch Hedberg","Mitch_Hedberg.jpg","false","I didn’t go to college\, but if I did\, I would’ve taken all my tests at a restaurant\, ’cause ‘The customer is always right.’"),
("Jim Rohn","Jim_Rohn.jpg","false","Formal education will make you a living. Self education will make you a fortune."),
("Jim Rohn","Jim_Rohn.jpg","false","The greatest reward in becoming a millionaire is not the amount of money that you earn. It is the kind of person that you have to become to become a millionaire in the first place."),
("Napoleon Hill","Napoleon_Hill.jpg","false","If you’re not learning while you’re earning\, you’re cheating yourself out of the better portion of your compensation."),
("Henry Ford","Henry_Ford.jpg","false","A business that makes nothing but money is a poor business."),
("Aristotle","Aristotle_Onassis.jpg",NULL,"“After a certain point\, money is meaningless. It ceases to be the goal. The game is what counts."),
("Michael Dunlop","Michael_Dunlop.jpg","false","I treat business a bit like a computer game. I count money as points. I’m doing really well: making lots of money and lots of points."),
("Adam Horwitz","Adam_Horwitz.jpg","false","All of my friends were doing babysitting jobs. I wanted money without the job."),
("Robert Bosch","Robert_Bosch.jpg","false","I don’t pay good wages because I have a lot of money; I have a lot of money because I pay good wages."),
("Ted Nicolas","Ted_Nicolas.jpg","false","Lend your friend $20. If he doesn’t pay you back then he’s not your friend. Money well spent."),
("Will Smith","Will_Smith.jpg","false","Money and success don’t change people; they merely amplify what is already there."),
("Agatha Christie","Agatha_Christie.png","false","The secret of getting ahead is getting started."),
("Peter Schultz","Peter_Schultz.jpg","false","Hire character. Train skill."),
("Dwight D. Eisenhower","Dwight_D._Eisenhower.jpg","false","In preparing for battle I have always found that plans are useless\, but planning is indispensable."),
("Michael Dunlop","Michael_Dunlop.jpg","false","You’ve got to stop doing all the things that people have tried\, tested\, and found out don’t work."),
("Thomas Edison","Thomas_Edison.jpg","false","I never perfected an invention that I did not think about in terms of the service it might give others… I find out what the world needs\, then I proceed to invent."),
("Catherine Cook","Catherine_Cook.jpg","false","If you’re not making mistakes\, then you’re not making decisions."),
("Bill Gates","Bill_Gates.jpg","false","Your most unhappy customers are your greatest source of learning."),
("Zig Ziglar","Zig_Ziglar.jpg","false","One can get anything if he is willing to help enough others get what they want."),
("Roy Ash","Roy_Ash.jpg","false","An entrepreneur tends to bite off a little more than he can chew hoping he’ll quickly learn how to chew it."),
("Nolan Bushnell","Nolan_Bushnell.jpg","false","The true entrepreneur is a doer\, not a dreamer."),
("Theodore Roosevelt","Theodore_Roosevelt.jpg","false","Whenever you are asked if you can do a job\, tell ’em\, ‘Certainly\, I can!’ Then get busy and find out how to do it."),
("Ben Weissenstein","Ben_Weissenstein.jpg","false","Everything started as nothing."),
("Michael Dunlop","Michael_Dunlop.jpg","false","If you start with nothing and end up with nothing\, there’s nothing lost."),
("Emil Motycka","Emil_Motycka.jpg","false","Start today\, not tomorrow. If anything\, you should have started yesterday."),
("Andrew Fashion","profile.png","false","Make it happen now\, not tomorrow. Tomorrow is a loser’s excuse."),
("Robert Orben","Robert_Orben.jpg","false","Every day I get up and look through the Forbes list of the richest people in America. If I’m not there\, I go to work."),
("Anonymous","profile.png","false","Entrepreneurship is living a few years of your life like most people won’t\, so that you can spend the rest of your life like most people can’t."),
("Babe Ruth","Babe_Ruth.jpg","false","Yesterday’s home runs don’t win today’s games."),
("Syed Balkhi","Syed_Balkhi.jpg","false","You should always stay hungry. Stay hungry\, so you can eat."),
("Anonymous","profile.png","false","If you’re not living life on the edge\, you’re taking up too much space."),
("Donald Trump","Donald_Trump.jpg","false","I wasn’t satisfied just to earn a good living. I was looking to make a statement."),
("Thomas Edison","Thomas_Edison.jpg","false","Opportunity is missed by most people because it is dressed in overalls and looks like work."),
("Jim Rohn","Jim_Rohn.jpg","false","You must either modify your dreams or magnify your skills."),
("Mark Twain","Mark_Twain.jpg","false","Keep away from people who try to belittle your ambitions. Small people always do that\, but the really great make you feel that you\, too\, can become great."),
("Ryan P. Allis","Ryan_P._Allis.png","false","Not a single person whose name is worth remembering lived a life of ease."),
("Joe Penna","Joe_Penna.jpg","false","If you think that you are going to love something\, give it a try. You’re going to kick yourself in the butt for the rest of your life if you don’t."),
("Chinese Proverb","profile.png","false","The best time to plant a tree is twenty years ago. The second best time is now."),
("Chinese Proverb","profile.png","false","If you want one year of prosperity\, grow grain. If you want ten years of prosperity\, grow trees. If you want one hundred years of prosperity\, grow people."),
("Japanese Proverb","profile.png","false","Vision without action is a daydream. Action without vision is a nightmare."),
("Chinese Proverb","profile.png","false","Sow a thought\, reap an action; sow an action\, reap a habit; sow a habit\, reap a character; sow a character\, reap a destiny."),
("Chinese Proverb","profile.png","false","A bad workman blames his tools."),
("Chinese Proverb","profile.png","false","A fall into a ditch makes you wiser."),
("Chinese Proverb","profile.png","false","Defeat isn’t bitter if you don’t swallow it."),
("Chinese Proverb","profile.png","false","The diamond cannot be polished without friction\, nor the man perfected without trials."),
("Chinese Proverb","profile.png","false","A jade stone is useless before it is processed; a man is good-for-nothing until he is educated."),
("Chinese Proverb","profile.png","false","A journey of a thousand miles begins with a single step."),
("Chinese Proverb","profile.png","false","The loftiest towers rise from the ground."),
("Asian Proverb","profile.png","false","Building a castle is difficult. Defending and maintaining it is harder still."),
("Chinese Proverb","profile.png","false","A person who says it cannot be done should not interrupt the man doing it."),
("Chinese Proverb","profile.png","false","All cats love fish but fear to wet their paws."),
("Chinese Proverb","profile.png","false","Don’t stand by the water and long for fish; go home and weave a net."),
("Hasidic Proverb","profile.png","false","Everyone should carefully observe which way his heart draws him\, and then choose that way with all his strength."),
("Chinese Proverb","profile.png","false","Failing to plan is planning to fail."),
("Chinese Proverb","profile.png","false","If you pay peanuts\, you get monkeys."),
("Chinese Proverb","profile.png","false","Make happy those who are near\, and those who are far will come."),
("Chinese Proverb","profile.png","false","Teachers open the door. You enter by yourself."),
("Unknown","profile.png","false","Find a job you love and you’ll never work a day in your life."),
("Michael Gerber","Michael_Gerber.jpg","false","The entrepreneur builds an enterprise; the technician builds a job."),
("Unknown.","profile.png","false","If you want to be inventive\,you have to be willing to fail."),
("Jim Collins","JimCollins.jpg","false","The challenge is not just to build a company that can endure; but to build one that is worthy of enduring."),
("Bill Gates","Bill_Gates.jpg","false","Success is a lousy teacher. It seduces smart people into thinking they can’t lose."),
("Chris Brogan","Chris_Brogan.jpg","false","Don’t treat your customers like a bunch of purses and wallets."),
("Unknown.","profile.png","false","Nine out of ten businesses fail; so I came up with a foolproof plan create ten businesses"),
("Unknown","profile.png","false","I’m not a businessman\,I'm a business\, man."),
("Unknown.","profile.png","false","If plan ‘A’ fails"),
("Winston Churchhill","Winston_Churchhill.jpg","false","We make a living by what we get. But we make a life by what we give."),
("Unknown.","profile.png","false","Believe that you will succeed"),
("Og Mandino","Og_Mandino.jpg","false","Victory comes only after many struggles and countless defeats."),
("Donald Trump","Donald_Trump.jpg","false","As long as you’re going to be thinking anyway\, think big."),
("General George Patton","General_George_Patton.jpg","false","Success is how high you bounce after you hit bottom"),
("Steve Jobs","Steve_Jobs.jpg","false","Remembering you are going to die is the best way I know to avoid the trap of thinking you have something to lose."),
("Steve Case","Steve_Case.jpg","false","It’s not about how to get started; its about how to get noticed."),
("John Shedd","John_Shedd.jpg","false","A ship in harbor is safe\, but that’s not what ships are for."),
("Thomas Edison","Thomas_Edison.jpg","false","If I find 10\,000 ways something won’t work\, I haven’t failed. I am not discouraged\, because every wrong attempt discarded is often a step forward."),
("Richard Branson","Richard_Branson.jpg","false","Business opportunities are like buses\, there’s always another one coming."),
("Jeff Clavier","Jeff_Clavier.jpg","false","If we don’t allow ourselves to make mistakes\, we will never invest in things that are radical."),
("Nolan Bushnell","Nolan_Bushnell.jpg","false","The critical ingredient is getting off your butt and doing something."),
("Maya Angelou","Maya_Angelou.jpg","false","Nothing will work unless you do."),
("Albert Einstein","Albert_Einstein.jpg","false","Try not to be a man of success\, but rather try to become a man of value."),
("John Lennon","John_Lennon.jpg","false","You won’t get anything unless you have the vision to imagine it."),
("John C. Maxwell","John_C._Maxwell.jpg","false","A man must be big enough to admit his mistakes\, smart enough to profit from them\, and strong enough to correct them."),
("David Ogilvy","David_Ogilvy.jpg","false","In the modern world of business\, it is useless to be a creative\, original thinker unless you can also sell what you create."),
("Tony Robbins","Tony_Robbins.jpg","false","Success is doing what you want\, where you want\, when you want\, with whom you want as much as you want."),
("Unknown","profile.png","false","If you don’t have a competitive advantage"),
("Zig Ziglar","Zig_Ziglar.jpg","false","You were born to win\, but to be a winner\, you must plan to win\, prepare to win\, and expect to win."),
("Mario Andretti","Mario_Andretti.jpg","false","If everything seems under control\, you’re just not going fast enough."),
("Unknown","profile.png","false","Don’t be trapped by dogma"),
("Yoda","profile.png","false","Do or do not. There is no try."),
("William Rosenberg","William_Rosenberg.jpg","false","Show me a person who never made a mistake\, and I will show you a person who never did anything."),
("Michael Dell","Michael_Dell.jpg","false","Ideas are commodity. Execution of them is not."),
("Evan Williams","Evan_Williams.jpg","false","User experience is everything. It always has been\, but it’s undervalued and underinvested in. If you don’t know user-centered design\, study it. Hire people who know it. Obsess over it. Live and breathe it. Get your whole company on board."),
("Winston Churchill","Winston_Churchill.jpg","false","A pessimist sees the difficulty in every opportunity; an optimist sees the opportunity in every difficulty."),
("Charles M. Schwab","Charles_M._Schwab.jpg","false","The man who does not work for the love of work but only for money is likely to neither make money nor find much fun in life."),
("Anthony Volodkin","Anthony_Volodkin.jpg","false","Be undeniably good. No marketing effort or social media buzzword can be a substitute for that."),
("Guy Kawasaki","Guy_Kawasaki.jpg","false","Ideas are easy. Implementation is hard."),
("John Rampton","John_Rampton.jpg","false","You can say anything to anyone\, but how you say it will determine how they will react."),
("Larry Page","Larry_Page.jpg","false","Always deliver more than expected."),
("Tamara Steffens\, Acompli","Tamara_Steffens.jpg","false","Assume you have 90 seconds with a new user before they decide to use your app or delete it."),
("Victoria Ransom","Victoria_Ransom.jpg","false","Even if you don’t have the perfect idea to begin with\, you can likely adapt."),
("Tim Westergen","Tim_Westergen.jpg","false","Make your team feel respected\, empowered and genuinely excited about the company’s mission."),
("Garrett Camp","Garrett_Camp.jpg","false","Stay self-funded as long as possible."),
("Sid Caesar\, Entertainer","Sid_Caesar.jpg","false","In between goals is a thing called life\, that has to be lived and enjoyed."),
("Lisa Stone","Lisa_Stone.jpg","false","Wonder what your customer really wants? Ask. Don’t tell."),
("Robert Kiyosaki","Robert_Kiyosaki.png","false","When times are bad is when the real entrepreneurs emerge."),
("Dave Thomas\, founder of Wendy’s","Dave_Thomas.jpg","false","What do you need to start a business? Three simple things: know your product better than anyone\, know your customer\, and have a burning desire to succeed."),
("Chris Dixon\, co-founder of Hunch","Chris_Dixon.jpg","false","Get big quietly\, so you don’t tip off potential competitors."),
("Drew Houston\, founder of Dropbox","Drew_Houston.jpg","false","Don’t worry about failure; you only have to be right once."),
("Unknown","profile.png","false","Your time is limited\, so don’t waste it living someone else’s life. Don’t be trapped by dogma"),
("Tony Hsieh\, Zappos.com CEO","Tony_Hsieh.jpg","false","Don’t be cocky. Don’t be flashy. There’s always someone better than you."),
("Ben Silbermann","Ben_Silbermann.jpg","false","Don’t take too much advice. Most people who have a lot of advice to give — with a few exceptions — generalize whatever they did. Don’t over-analyze everything. I myself have been guilty of over-thinking problems. Just build things and find out if they work."),
("Todd Garland","Todd_Garland.jpg","false","Openly share and talk to people about your idea. Use their lack of interest or doubt to fuel your motivation to make it happen."),
("Yvon Chouinard","Yvon_Chouinard.jpg","false","How you climb a mountain is more important than reaching the top."),
("Booker T. Washington","profile.png","false","Associate yourself with people of good quality\, for it is better to be alone than in bad company."),
("Bill Gates","Bill_Gates.jpg","false","It’s fine to celebrate success but it is more important to heed the lessons of failure."),
("Warren Buffett\, Investor","Warren_Buffett.jpg","false","It takes 20 years to build a reputation and five minutes to ruin it. If you think about that\, you’ll do things differently."),
("Zig Ziglar","Zig_Ziglar.jpg","false","Statistics suggest that when customers complain\, business owners and managers ought to get excited about it. The complaining customer represents a huge opportunity for more business."),
("Christopher Morley\, journalist","Christopher_Morley.jpg","false","There is only one success- to be able to spend your life in your own way."),
("Jim Rohn\, author and speaker","Jim_Rohn.jpg","false","Formal education will make you a living; self-education will make you a fortune."),
("Henry Ford","Henry_Ford.jpg","false","When everything seems to be going against you\, remember that the airplane takes off against the wind\, not with it."),
("Jimmy Spithill","Jimmy_Spithill.jpg","false","Rarely have I seen a situation where doing less than the other guy is a good strategy."),
("Wayne Gretzky","Wayne_Gretzky.jpg","false","You miss 100 percent of the shots you don’t take."),
("Chinese proverb","profile.png","false","The best time to plant a tree was 20 years ago. The second best time is now."),
("Marc Benioff\, CEO of Salesforce","Marc_Benioff.jpg","false","The secret to successful hiring is this: look for the people who want to change the world."),
("Mark Twain\, author","Mark_Twain.jpg","false","Twenty years from now\, you will be more disappointed by the things that you didn’t do than by the ones you did do\, so throw off the bowlines\, sail away from safe harbor\, catch the trade winds in your sails. Explore\, Dream\, Discover."),
("Kevin Systrom\, co-founder of Instagram","Kevin_Systrom.jpg","false","If you’ve got an idea\, start today. There’s no better time than now to get going. That doesn’t mean quit your job and jump into your idea 100% from day one\, but there’s always small progress that can be made to start the movement."),
("Richard Harroch\, Venture Capitalist","Aristotle_Onassis.jpg","false","It’s almost always harder to raise capital than you thought it would be\, and it always takes longer. So plan for that."),
("Timothy Ferriss","Timothy_Ferriss.jpg","false","For all of the most important things\, the timing always sucks. Waiting for a good time to quit your job? The stars will never align and the traffic lights of life will never all be green at the same time. The universe doesn’t conspire against you\, but it doesn’t go out of its way to line up the pins either. Conditions are never perfect. “Someday is a disease that will take your dreams to the grave with you. Pro and con lists are just as bad. If it’s important to you and you want to do it “eventually\, just do it and correct course along the way."),
("Matt Mullenweg\, founder of Automattic","Matt_Mullenweg.jpg","false","I don’t have big ideas. I sometimes have small ideas\, which seem to work out."),
("Tom Kelley\, Ideo partner","Tom_Kelley.jpg","false","Fail often so you can succeed sooner."),
("Malcolm Forbes","Malcolm_Forbes.jpg","false","When you cease to dream you cease to live."),
("Dr. Napoleon Hill","Napoleon_Hill.jpg","false","Whatever the mind can conceive and believe\, the mind can achieve."),
("Sean Parker\, co-founder of Napster","Sean_Parker.jpg","false","Running a start-up is like eating glass. You just start to like the taste of your own blood."),
("Mark Zuckerberg\, founder of Facebook","Mark_Zuckerberg.jpg","false","My number one piece of advice is: you should learn how to program."),
("Walt Disney\, co-founder of the Walt Disney Company","Walt_Disney.jpg","false","The way to get started is to quit talking and begin doing."),
("Matt Mickiewicz\, co-founder of 99 Designs","Matt_Mickiewicz.jpg","false","The pace of change for entrepreneurs is rapidly accelerating\, and the cost and risk of launching a new business and getting off the ground is just amazing. The ability to gain user feedback really quickly and adapt to what your consumers want is totally different with the web as it is now. But finding a new market\, helping people and taking that original idea and turning it into a business is really exciting right now."),
("Matthew Inman","Matthew_Inman.jpg","false","Building and hanging on to an audience is the biggest role of social media."),
("David Karp\, founder of Tumblr","David_Karp.jpg","false","Every feature has some maintenance cost\, and having fewer features lets us focus on the ones we care about and make sure they work very well."),
("Noah Everett\, founder of Twitpic","profile.png","false","A poorly implemented feature hurts more than not having it at all."),
(" Peter F. Drucker\, educator and author","Peter_F_ Drucker.jpg","false","This defines entrepreneur and entrepreneurship"),
("Richard Branson\, founder of Virgin Group","Richard_Branson.jpg","false","You don’t learn to walk by following rules. You learn by doing and falling over."),
("Reid Hoffman\, co-founder of Linkedin","Reid_Hoffman.jpg","false","The fastest way to change yourself is to hang out with people who are already the way you want to be."),
("Howard Schultz\, CEO of Starbucks","Howard_Schultz.jpg","false","Risk more than others think is safe. Dream more than others think is practical."),
("Steve Case\, co-founder of AOL","Steve_Case.jpg","false","You shouldn’t focus on why you can’t do something\, which is what most people do. You should focus on why perhaps you can\, and be one of the exceptions."),
("Nolan Bushnell\, founder of Atari","Nolan_Bushnell.jpg","false","The critical ingredient is getting off your butt and doing something. It’s as simple as that. A lot of people have ideas\, but there are few who decide to do something about them now. Not tomorrow. Not next week. But today. The true entrepreneur is a doer not a dreamer."),
("Napoleon Hill\, author","Napoleon_Hill.jpg","false","If you cannot do great things\, do small things in a great way."),
("Bo Bennet\, author and entreprenuer","Bo_Bennet.jpg","false","Success is not what you have\, but who you are."),
("Jeff Bezos\, founder and CEO of Amazon.com","Jeff_Bezos.jpg","false","One of the huge mistakes people make is that they try to force an interest on themselves. You don’t choose your passions; your passions choose you."),
("Larry Page\, CEO of Google","Larry_Page.jpg","false","Lots of companies don’t succeed over time. What do they fundamentally do wrong? They usually miss the future."),
("Cher Wang\, CEO of HTC","profile.png","false","It takes humility to realize that we don’t know everything\, not to rest on our laurels and know that we must keep learning and observing. If we don’t\, we can be sure some startup will be there to take our place."),
("Kevin Plank\, CEO of Under Armour","Kevin_Plank.jpg","false","There’s an entrepreneur right now\, scared to death\, making excuses\, saying\, ‘It’s not the right time just yet.’ There’s no such thing as a good time. Get out of your garage and go take a chance\, and start your business."),
("Peter Berg\, founder of October Three","Peter_Berg.jpg","false","Be really picky with your hiring\, and hire the absolute best people you possibly can. People are the most important component of almost every business\, and attracting the best talent possible is going to make a huge difference."),
("Gary Comer\, founder of Land’s End","Gary_Comer.jpg","false","Worry about being better; bigger will take care of itself. Think one customer at a time and take care of each one the best way you can."),
("Jim Koch\, founder of Boston Beer Co.","Jim_Koch.jpg","false","You have a viable business only if your product is either better or cheaper than the alternatives. If it’s not one or the other\, you might make some money at first\, but it’s not a sustainable business."),
("Casey Neistat\, filmmaker","Casey_Neistat.jpg","false","Every time I took these bigger risks\, the opportunity for a bigger payout was always there."),
("Ron Shaich","Ron_Shaich.png","false","If you can do something to get somebody excited — not everybody — but if you can be the best for somebody\, then you can win."),
("Thomas J. Watson\, businessman","Thomas_J._Watson.jpg","false","Would you like me to give you a formula for success? It’s quite simple\, really: Double your rate of failure. You are thinking of failure as the enemy of success. But it isn’t at all. You can be discouraged by failure or you can learn from it\, so go ahead and make mistakes. Make all you can. Because remember that’s where you will find success."),
("Tony Robbins\, motivational speaker","Tony_Robbins.jpg","false","People who succeed have momentum. The more they succeed\, the more they want to succeed\, and the more they find a way to succeed. Similarly\, when someone is failing\, the tendency is to get on a downward spiral that can even become a self-fulfilling prophecy."),
("Franklin D. Roosevelt","Franklin_D._Roosevelt.jpg","false","The only limit to our realization of tomorrow will be our doubts of today."),
("Bruce Lee","Bruce_Lee.jpg","false","The successful warrior is the average man\, with laser-like focus."),
("Japanese proverb","profile.png","false","Fall seven times and stand up eight."),
("Roy L. Smith\, animator and film director","Roy_L._Smith.jpg","false","The successful man is the one who finds out what is the matter with his business before his competitors do."),
("Seth Godin\, author and speaker","Seth_Godin.jpg","false","There’s no shortage of remarkable ideas\, what’s missing is the will to execute them."),
("Charles F. Kettering\, inventor","Charles_F._Kettering.jpg","false","Keep on going\, and the chances are that you will stumble on something\, perhaps when you are least expecting it. I never heard of anyone ever stumbling on something sitting down."),
("David Brinkley\, newscaster","David_Brinkley.jpg","false","A successful man is one who can lay a firm foundation with the bricks others have thrown at him."),
("Albert Einstein","Albert_Einstein.jpg","false","Everyone is a genius. But if you judge a fish by its ability to climb a tree\, it will spend its whole life believing it is stupid."),
("David Rockefeller","David_Rockefeller.jpg","false","Success in business requires training and discipline and hard work. But if you’re not frightened by these things\, the opportunities are just as great today as they ever were."),
("George Eliot","George_Eliot.jpg","false","It is never too late to be what you might have been."),
("Stephen Covey","Stephen_Covey.jpg","false","I am not a product of my circumstances. I am a product of my decisions."),
("Aristotle","Aristotle_Onassis.jpg","false","There is only one way to avoid criticism: Do nothing\, say nothing\, and be nothing."),
("Farrah Gray","Farrah_Gray.jpg","false","Build your own dreams\, or someone else will hire you to build theirs."),
("Beverly Sills\, operatic soprano","Beverly_Sills.jpg","false","You may be disappointed if you fail\, but you are doomed if you don’t try.");